image: registry.gitlab.com/satoshilabs/trezor/trezor-firmware/environment

variables:
  SDL_VIDEODRIVER: "dummy"
  XDG_RUNTIME_DIR: "/var/tmp"


# Core

build core firmware:
  stage: build
  script:
    - cd core
    - pipenv run make build_cross
    - pipenv run make build_boardloader
    - pipenv run make build_bootloader
    - pipenv run make build_prodtest
    - pipenv run make build_firmware
    - pipenv run make sizecheck
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
    - core/build/firmware/firmware.bin
    - core/build/bootloader/bootloader.bin
    expire_in: 1 week

build core firmware bitcoinonly:
  stage: build
  variables:
    BITCOIN_ONLY: "1"
  script:
    - cd core
    - pipenv run make build_firmware

build core unix:
  stage: build
  script:
    - cd core
    - pipenv run make build_unix

build core unix bitcoinonly:
  stage: build
  variables:
    BITCOIN_ONLY: "1"
  script:
    - cd core
    - pipenv run make build_unix

build core unix frozen:
  stage: build
  script:
    - cd core
    - pipenv run make build_unix_frozen
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    untracked: true
    expire_in: 1 day


# Crypto

build crypto:
  stage: build
  script:
    - cd crypto
    - pipenv run make
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    untracked: true
    expire_in: 1 day


# Legacy

# TODO: add clang https://github.com/trezor/trezor-firmware/issues/44
build legacy firmware:
  stage: build
  script:
    - cd legacy
    - pipenv run script/cibuild
    - pipenv run make -C bootloader
    - pipenv run make -C demo

build legacy firmware debug:
  stage: build
  variables:
    DEBUG_LINK: "1"
  script:
    - cd legacy
    - pipenv run script/cibuild

build legacy firmware bitcoinonly:
  stage: build
  variables:
    BITCOIN_ONLY: "1"
  script:
    - cd legacy
    - pipenv run script/cibuild

build legacy emu:
  stage: build
  variables:
    DEBUG_LINK: "1"
    EMULATOR: "1"
  script:
    - cd legacy
    - pipenv run script/cibuild
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    untracked: true
    expire_in: 1 day

build legacy emu bitcoinonly:
  stage: build
  variables:
    BITCOIN_ONLY: "1"
    DEBUG_LINK: "1"
    EMULATOR: "1"
  script:
    - cd legacy
    - pipenv run script/cibuild
